USE `DB-RTST_2101`;

CREATE TABLE IF NOT EXISTS `TB-Session` (
	`Session` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
	`Member` BIGINT(20) UNSIGNED NOT NULL,
	`Key` CHAR(36) NOT NULL COLLATE 'utf8mb4_general_ci',
	`IP` VARCHAR(15) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
	`Logined` TIMESTAMP NOT NULL DEFAULT current_timestamp(),
	`Expired` DATETIME NOT NULL,
	PRIMARY KEY (`Session`) USING BTREE,
	UNIQUE INDEX `Key` (`Key`) USING BTREE,
	INDEX `Expired` (`Expired`) USING BTREE
) COLLATE='utf8mb4_general_ci' ENGINE=InnoDB;
